# Generated by Django 4.2.11 on 2024-03-29 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('column', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': '6. Annual',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('column', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': '4. Month',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': '2. Parameter',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '1. Regions',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('column', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': '5. Seasons',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': '3. Years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params_season', to='weather_app.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_season', to='weather_app.region')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_season', to='weather_app.season')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_season', to='weather_app.year')),
            ],
            options={
                'verbose_name_plural': '7. Seasons Data',
            },
        ),
        migrations.CreateModel(
            name='MonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_month', to='weather_app.month')),
                ('params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params_month', to='weather_app.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_month', to='weather_app.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_month', to='weather_app.year')),
            ],
            options={
                'verbose_name_plural': '8. Monthly Data ',
            },
        ),
        migrations.CreateModel(
            name='AnnualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('column', models.IntegerField(default=1)),
                ('params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params_annual', to='weather_app.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_annual', to='weather_app.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_annual', to='weather_app.year')),
            ],
            options={
                'verbose_name_plural': '9. Annual Data ',
            },
        ),
    ]
